//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.3901.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAGlobalChangeUIModel
{

/// <summary>
/// Represents the UI model for the 'Add random attribute value (AIA)' data form
/// </summary>

public partial class @AIAAddRandomAttributeUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _attributecategoryid;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _randminvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.IntegerField _randmaxvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _comment;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _removeunqualified;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _overwriteexistingvalue;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _startdate;
    private global::Blackbaud.AppFx.UIModeling.Core.DateField _enddate;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _queryedit;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public @AIAAddRandomAttributeUIModel() : base()
	{


        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _attributecategoryid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _randminvalue = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _randmaxvalue = new global::Blackbaud.AppFx.UIModeling.Core.IntegerField();
        _comment = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _removeunqualified = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _overwriteexistingvalue = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _startdate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _enddate = new global::Blackbaud.AppFx.UIModeling.Core.DateField();
        _queryedit = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        this.UserInterfaceUrl = "browser/htmlforms/custom/AIA/AIAAddRandomAttribute.html";

        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "Record type";
        _recordtypeid.Required = true;
        _recordtypeid.SimpleDataListId = new System.Guid("86cf30ca-70c4-4cd9-a70f-50814d706b98");
        this.Fields.Add(_recordtypeid);
        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_attributecategoryid
        //
        _attributecategoryid.Name = "ATTRIBUTECATEGORYID";
        _attributecategoryid.Caption = "Category";
        _attributecategoryid.Required = true;
        _attributecategoryid.SimpleDataListId = new System.Guid("cb839c08-e56b-480b-a92c-d579c8d95277");
        _attributecategoryid.Parameters.Add(new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("RECORDTYPEID", "Fields!RECORDTYPEID"));
        this.Fields.Add(_attributecategoryid);
        //
        //_randminvalue
        //
        _randminvalue.Name = "RANDMINVALUE";
        _randminvalue.Caption = "Minimum value";
        this.Fields.Add(_randminvalue);
        //
        //_randmaxvalue
        //
        _randmaxvalue.Name = "RANDMAXVALUE";
        _randmaxvalue.Caption = "Maximum value";
        this.Fields.Add(_randmaxvalue);
        //
        //_comment
        //
        _comment.Name = "COMMENT";
        _comment.Caption = "Comment";
        _comment.MaxLength = 255;
        this.Fields.Add(_comment);
        //
        //_removeunqualified
        //
        _removeunqualified.Name = "REMOVEUNQUALIFIED";
        _removeunqualified.Caption = "Remove attribute from unqualified records";
        this.Fields.Add(_removeunqualified);
        //
        //_overwriteexistingvalue
        //
        _overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE";
        _overwriteexistingvalue.Caption = "Overwrite existing values";
        _overwriteexistingvalue.Value = true;
        this.Fields.Add(_overwriteexistingvalue);
        //
        //_startdate
        //
        _startdate.Name = "STARTDATE";
        _startdate.Caption = "Start date";
        this.Fields.Add(_startdate);
        //
        //_enddate
        //
        _enddate.Name = "ENDDATE";
        _enddate.Caption = "End date";
        this.Fields.Add(_enddate);
        //
        //_queryedit
        //
        _queryedit.Name = "QUERYEDIT";
        _queryedit.Caption = "";
        _idsetregisterid.LinkedActions.Add(_queryedit);
        this.Actions.Add(_queryedit);

		OnCreated();

	}

    /// <summary>
    /// Record type
    /// </summary>
    [System.ComponentModel.Description("Record type")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    /// <summary>
    /// Category
    /// </summary>
    [System.ComponentModel.Description("Category")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @ATTRIBUTECATEGORYID {
		get { return _attributecategoryid; }
	}

    /// <summary>
    /// Minimum value
    /// </summary>
    [System.ComponentModel.Description("Minimum value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @RANDMINVALUE {
		get { return _randminvalue; }
	}

    /// <summary>
    /// Maximum value
    /// </summary>
    [System.ComponentModel.Description("Maximum value")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.IntegerField @RANDMAXVALUE {
		get { return _randmaxvalue; }
	}

    /// <summary>
    /// Comment
    /// </summary>
    [System.ComponentModel.Description("Comment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @COMMENT {
		get { return _comment; }
	}

    /// <summary>
    /// Remove attribute from unqualified records
    /// </summary>
    [System.ComponentModel.Description("Remove attribute from unqualified records")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @REMOVEUNQUALIFIED {
		get { return _removeunqualified; }
	}

    /// <summary>
    /// Overwrite existing values
    /// </summary>
    [System.ComponentModel.Description("Overwrite existing values")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @OVERWRITEEXISTINGVALUE {
		get { return _overwriteexistingvalue; }
	}

    /// <summary>
    /// Start date
    /// </summary>
    [System.ComponentModel.Description("Start date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @STARTDATE {
		get { return _startdate; }
	}

    /// <summary>
    /// End date
    /// </summary>
    [System.ComponentModel.Description("End date")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.DateField @ENDDATE {
		get { return _enddate; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3901.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @QUERYEDIT {
		get { return _queryedit; }
	}

}

}
