//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAGlobalChangeUIModel
{

/// <summary>
/// Represents the UI model for the 'Make constituent inactive (AIA)' data form
/// </summary>

public partial class @AIAMakeConstituentInactiveUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> _constituentinactivityreasoncodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _details;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _updateexistinginactive;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _editquery;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIAMakeConstituentInactiveUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _constituentinactivityreasoncodeid = new global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid>();
        _details = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _updateexistinginactive = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _editquery = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_constituentinactivityreasoncodeid
        //
        _constituentinactivityreasoncodeid.Name = "CONSTITUENTINACTIVITYREASONCODEID";
        _constituentinactivityreasoncodeid.Caption = "Reason";
        _constituentinactivityreasoncodeid.Required = true;
        _constituentinactivityreasoncodeid.SimpleDataListId = new System.Guid("71b29b04-d70f-4d38-bab1-e44a2528d0e8");
        this.Fields.Add(_constituentinactivityreasoncodeid);
        //
        //_details
        //
        _details.Name = "DETAILS";
        _details.Caption = "Details";
        _details.MaxLength = 300;
        this.Fields.Add(_details);
        //
        //_updateexistinginactive
        //
        _updateexistinginactive.Name = "UPDATEEXISTINGINACTIVE";
        _updateexistinginactive.Caption = "Update existing inactive reasons";
        this.Fields.Add(_updateexistinginactive);
        //
        //_editquery
        //
        _editquery.Name = "EDITQUERY";
        _editquery.Caption = "";
        _idsetregisterid.LinkedActions.Add(_editquery);
        this.Actions.Add(_editquery);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Reason
    /// </summary>
    [System.ComponentModel.Description("Reason")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SimpleDataListField<System.Guid> @CONSTITUENTINACTIVITYREASONCODEID {
		get { return _constituentinactivityreasoncodeid; }
	}

    /// <summary>
    /// Details
    /// </summary>
    [System.ComponentModel.Description("Details")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @DETAILS {
		get { return _details; }
	}

    /// <summary>
    /// Update existing inactive reasons
    /// </summary>
    [System.ComponentModel.Description("Update existing inactive reasons")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @UPDATEEXISTINGINACTIVE {
		get { return _updateexistinginactive; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @EDITQUERY {
		get { return _editquery; }
	}

}

}
