//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.2616.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace AIAGlobalChangeUIModel
{

/// <summary>
/// Represents the UI model for the 'Update revenue metadata (AIA)' data form
/// </summary>

public partial class @AIAUpdateRevenueMetadataUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _idsetregisterid;
    private global::Blackbaud.AppFx.UIModeling.Core.GuidField _recordtypeid;
    private global::Blackbaud.AppFx.UIModeling.Core.LongField _findernumber;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _sourcecode;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _appealid;
    private global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> _mailingid;
    private global::Blackbaud.AppFx.UIModeling.Core.CodeTableField _channelcodeid;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction _queryedit;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public @AIAUpdateRevenueMetadataUIModel() : base()
	{


        _idsetregisterid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _recordtypeid = new global::Blackbaud.AppFx.UIModeling.Core.GuidField();
        _findernumber = new global::Blackbaud.AppFx.UIModeling.Core.LongField();
        _sourcecode = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _appealid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _mailingid = new global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid>();
        _channelcodeid = new global::Blackbaud.AppFx.UIModeling.Core.CodeTableField();
        _queryedit = new global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction();

        this.UserInterfaceUrl = "browser/htmlforms/custom/AIA/AIAUpdateRevenueMetadata.html";

        //
        //_idsetregisterid
        //
        _idsetregisterid.Name = "IDSETREGISTERID";
        _idsetregisterid.Caption = "Selection";
        _idsetregisterid.Required = true;
        _idsetregisterid.SearchListId = new System.Guid("98d0070e-c4a7-495b-a438-2ac12da79068");
        _idsetregisterid.EnableQuickFind = true;
        _idsetregisterid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "RECORDTYPEID", Caption = "Record type", ReadOnly = true, DefaultValueText = "Fields!RECORDTYPEID"});
        _idsetregisterid.SystemSearchType = global::Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection;
        this.Fields.Add(_idsetregisterid);
        //
        //_recordtypeid
        //
        _recordtypeid.Name = "RECORDTYPEID";
        _recordtypeid.Caption = "RECORDTYPEID";
        _recordtypeid.Visible = false;
        _recordtypeid.DBReadOnly = true;
        this.Fields.Add(_recordtypeid);
        //
        //_findernumber
        //
        _findernumber.Name = "FINDERNUMBER";
        _findernumber.Caption = "Finder number";
        _findernumber.DoNotApplyFormat = true;
        this.Fields.Add(_findernumber);
        //
        //_sourcecode
        //
        _sourcecode.Name = "SOURCECODE";
        _sourcecode.Caption = "Source code";
        _sourcecode.MaxLength = 50;
        this.Fields.Add(_sourcecode);
        //
        //_appealid
        //
        _appealid.Name = "APPEALID";
        _appealid.Caption = "Appeal";
        _appealid.SearchListId = new System.Guid("a3b8a1b8-3a78-446a-9041-f29c08e2c8c9");
        _appealid.EnableQuickFind = true;
        _appealid.SearchListAddForms.Add(new global::Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(new System.Guid("2736a8b5-ab2e-4330-ba15-98818321c643"), "Add"));
        this.Fields.Add(_appealid);
        //
        //_mailingid
        //
        _mailingid.Name = "MAILINGID";
        _mailingid.Caption = "Mailing";
        _mailingid.SearchListId = new System.Guid("349397cb-e2dd-43e8-a4ca-af5647c91d99");
        _mailingid.EnableQuickFind = true;
        _mailingid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "STATUS", Caption = "Status", Hidden = true, ReadOnly = true, DefaultValueText = "1"});
        _mailingid.SearchFieldOverrides.Add(new global::Blackbaud.AppFx.UIModeling.Core.FieldOverride() {FieldId = "INCLUDEAPPEALMAILINGS", Caption = "Include appeal mailings", Hidden = true, ReadOnly = true, DefaultValueText = "true"});
        this.Fields.Add(_mailingid);
        //
        //_channelcodeid
        //
        _channelcodeid.Name = "CHANNELCODEID";
        _channelcodeid.Caption = "Channel";
        _channelcodeid.CodeTableName = "CHANNELCODE";
        this.Fields.Add(_channelcodeid);
        //
        //_queryedit
        //
        _queryedit.Name = "QUERYEDIT";
        _queryedit.Caption = "";
        _idsetregisterid.LinkedActions.Add(_queryedit);
        this.Actions.Add(_queryedit);

		OnCreated();

	}

    /// <summary>
    /// Selection
    /// </summary>
    [System.ComponentModel.Description("Selection")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @IDSETREGISTERID {
		get { return _idsetregisterid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GuidField @RECORDTYPEID {
		get { return _recordtypeid; }
	}

    /// <summary>
    /// Finder number
    /// </summary>
    [System.ComponentModel.Description("Finder number")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.LongField @FINDERNUMBER {
		get { return _findernumber; }
	}

    /// <summary>
    /// Source code
    /// </summary>
    [System.ComponentModel.Description("Source code")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @SOURCECODE {
		get { return _sourcecode; }
	}

    /// <summary>
    /// Appeal
    /// </summary>
    [System.ComponentModel.Description("Appeal")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @APPEALID {
		get { return _appealid; }
	}

    /// <summary>
    /// Mailing
    /// </summary>
    [System.ComponentModel.Description("Mailing")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.SearchListField<System.Guid> @MAILINGID {
		get { return _mailingid; }
	}

    /// <summary>
    /// Channel
    /// </summary>
    [System.ComponentModel.Description("Channel")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.CodeTableField @CHANNELCODEID {
		get { return _channelcodeid; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.2616.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowQueryFormUIAction @QUERYEDIT {
		get { return _queryedit; }
	}

}

}
